# remote_theme: just-the-docs/just-the-docs
theme: just-the-docs

incremental: true

jdk_distribution: "21.0.6-librca"

exclude: 
  - lab_SAVE
  - lectures_SAVE
  - hwk_SAVE

course: "CMPSC 156"
title: "CS156 s26"
quarter: "Spring 2026"
QXX: s26
qxx: s26
baseurl: "/s26"
slack_help_lecture_discussion: TBD
sample_team: s26-04

ta_list_full: Daniel Jensen, Kiril Aristarkhov
la_list_full: Andrew Chen, Austin Chan, Derek Kirschbaum, Divyani Punj 
discussion_section_day: Wednesday
discussion_section_times: 5pm, 6pm

help_windows_link: https://ucsb-cs156-s26.slack.com/archives/tbd
help_macos_link: https://ucsb-cs156-s26.slack.com/archives/tbd
help_lecture_discussion: https://ucsb-cs156-s26.slack.com/archives/tbd

mermaid:
  # Version of mermaid library
  # Pick an available version from https://cdn.jsdelivr.net/npm/mermaid/
  version: "9.1.3"

# Aux links for the upper right navigation
aux_links:
  "CS156 main website":
    - "https://ucsb-cs156.github.io/"
  "github":
    - "//github.com/ucsb-cs156-s26"
  "Canvas":
    - "https://ucsb.instructure.com/courses/32781"

# TODO: replace canvas link above with specific one
# such as https://www.canvas.ucsb.edu/courses/12345

# Footer last edited timestamp
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html

# Footer "Edit this page on GitHub" link text
gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "Edit this page on GitHub."
gh_edit_repository: "https://github.com/ucsb-cs156/s26" # the github URL for your repo
gh_edit_branch: "main" # the branch that your docs is served from
gh_edit_view_mode: "edit" # "tree" or "edit" if you want the user to jump into the editor immediately


# Collections for website data
collections:
  modules:
  staffers:
    permalink: "/:path/"
    output: true
  lectures:
    permalink: "/lectures/:path/"
    output: true
  hwk:
    permalink: "/hwk/:path/"
    output: true
# Default layouts for each collection type
defaults:
  - scope:
      type: lectures
    values:
      layout: default
  - scope:
      type: hwk
    values:
      layout: default
  - scope:
      path: ""
      type: staffers
    values:
      layout: staffer
      subpath: "/assets/images/"

teams: 
  - team: s26-01
    dokku: "01"
    team01_project: "4"
    team02_project: "20"
    legacy_project: "tbd"
    legacy_kanban: "tbd"
    slack: https://ucsb-cs156-s26.slack.com/archives/C0AQ16HHTLN
  - team: s26-02
    dokku: "02"
    team01_project: "5"
    team02_project: "21"
    legacy_project: "tbd"
    legacy_kanban: "tbd"
    slack: https://ucsb-cs156-s26.slack.com/archives/C0AQ6RWK51S
  - team: s26-03
    dokku: "03"
    team01_project: "6"
    team02_project: "22"
    legacy_project: "tbd"
    legacy_kanban: "tbd"
    slack: https://ucsb-cs156-s26.slack.com/archives/C0AQ6RSHJ76
  - team: s26-04
    dokku: "04"
    team01_project: "7"
    team02_project: "23"
    legacy_project: "tbd"
    legacy_kanban: "tbd"
    slack: https://ucsb-cs156-s26.slack.com/archives/C0APMQJ07EK
  - team: s26-05
    dokku: "05"
    team01_project: "8"
    team02_project: "24"
    legacy_project: "tbd"
    legacy_kanban: "tbd"
    slack: https://ucsb-cs156-s26.slack.com/archives/C0AQXGGHH3J
  - team: s26-06
    dokku: "06"
    team01_project: "9"
    team02_project: "25"
    legacy_project: "tbd"
    legacy_kanban: "tbd"
    slack: https://ucsb-cs156-s26.slack.com/archives/C0AQG5DHA81
  - team: s26-07
    dokku: "07"
    team01_project: "10"
    team02_project: "26"
    legacy_project: "tbd"
    legacy_kanban: "tbd"
    slack: https://ucsb-cs156-s26.slack.com/archives/C0APWSJ513M
  - team: s26-08
    dokku: "08"
    team01_project: "11"
    team02_project: "27"
    legacy_project: "tbd"
    legacy_kanban: "tbd"
    slack: https://ucsb-cs156-s26.slack.com/archives/C0AQ38D61MG
  - team: s26-09
    dokku: "09"
    team01_project: "12"
    team02_project: "28"
    legacy_project: "tbd"
    legacy_kanban: "tbd"
    slack: https://ucsb-cs156-s26.slack.com/archives/C0AQXGBTU9W
  - team: s26-10
    dokku: "10"
    team01_project: "13"
    team02_project: "29"
    legacy_project: "tbd"
    legacy_kanban: "tbd"
    slack: https://ucsb-cs156-s26.slack.com/archives/C0AQXGH3880
  - team: s26-11
    dokku: "11"
    team01_project: "14"
    team02_project: "30"
    legacy_project: "tbd"
    legacy_kanban: "tbd"
    slack: https://ucsb-cs156-s26.slack.com/archives/C0AQ6RWM6HJ
  - team: s26-12
    dokku: "12"
    team01_project: "15"
    team02_project: "31"
    legacy_project: "tbd"
    legacy_kanban: "tbd"
    slack: https://ucsb-cs156-s26.slack.com/archives/C0AQXGGPVQQ
  - team: s26-13
    dokku: "13"
    team01_project: "16"
    team02_project: "32"
    legacy_project: "tbd"
    legacy_kanban: "tbd"
    slack: https://ucsb-cs156-s26.slack.com/archives/C0AQ38D37RQ
  - team: s26-14
    dokku: "14"
    team01_project: "17"
    team02_project: "33"
    legacy_project: "tbd"
    legacy_kanban: "tbd"
    slack: https://ucsb-cs156-s26.slack.com/archives/C0AQ16HUW22
  - team: s26-15
    dokku: "15"
    team01_project: "18"
    team02_project: "34"
    legacy_project: "tbd"
    legacy_kanban: "tbd"
    slack: https://ucsb-cs156-s26.slack.com/archives/C0AQ6RXBAJY
  - team: s26-16
    dokku: "16"
    team01_project: "19"
    team02_project: "35"
    legacy_project: "tbd"
    legacy_kanban: "tbd"
    slack: https://ucsb-cs156-s26.slack.com/archives/C0APZRQBQ9K
